package generator

import (
	"fmt"
	"gitlab.tech.mvideo.ru/mvideoru/debug/models"
	"go/format"
	"path"
	"sort"
	"strings"
	"unicode"
)

func GenerateSource(pkgName string, structs []models.StructInfo, imports map[string]string) ([]byte, error) {
	var b strings.Builder

	//b.WriteString("// Code generated by getter-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n", pkgName)

	if len(imports) > 0 {
		// Sort import paths for deterministic output
		paths := make([]string, 0, len(imports))
		for _, p := range imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)

		// Build reverse map: quoted path -> alias
		aliasOf := make(map[string]string)
		for alias, p := range imports {
			aliasOf[p] = alias
		}

		if len(paths) == 1 {
			p := paths[0]
			alias := aliasOf[p]
			defaultAlias := path.Base(strings.Trim(p, `"`))
			if alias != defaultAlias {
				fmt.Fprintf(&b, "\nimport %s %s\n", alias, p)
			} else {
				fmt.Fprintf(&b, "\nimport %s\n", p)
			}
		} else {
			b.WriteString("\nimport (\n")
			for _, p := range paths {
				alias := aliasOf[p]
				defaultAlias := path.Base(strings.Trim(p, `"`))
				if alias != defaultAlias {
					fmt.Fprintf(&b, "\t%s %s\n", alias, p)
				} else {
					fmt.Fprintf(&b, "\t%s\n", p)
				}
			}
			b.WriteString(")\n")
		}
	}

	for _, s := range structs {
		for _, f := range s.Fields {
			publicName := capitalize(f.Name)
			fmt.Fprintf(&b, "\nfunc (%s *%s) %s() %s {\n\treturn %s.%s\n}\n",
				s.RecvName, s.Name, publicName, f.TypeName, s.RecvName, f.Name)
		}
	}

	return format.Source([]byte(b.String()))
}

func capitalize(s string) string {
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
