package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type fieldInfo struct {
	name     string
	typeName string
}

type structInfo struct {
	name     string
	recvName string
	fields   []fieldInfo
}

type extractedFileData struct {
	imports []*ast.ImportSpec
	decls   []ast.Decl
}

func main() {
	dirs := os.Args[1:]
	if len(dirs) == 0 {
		dirs = []string{"."}
	}
	for _, dir := range dirs {
		if err := processDir(dir); err != nil {
			log.Fatalf("getter-gen: %s: %v", dir, err)
		}
	}
}

func processDir(dir string) error {
	fset, files, err := parseDir(dir)
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return nil
	}

	pkgName := files[0].Name.Name

	fileData := extractFileData(files)

	allImports := collectImports(fileData.imports)
	structs := collectStructs(fset, fileData.decls)
	if len(structs) == 0 {
		return nil
	}

	needed := neededImports(structs, allImports)
	src, err := generateSource(pkgName, structs, needed)
	if err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(dir, fmt.Sprintf("%s_getters.go", files[0].Name)), src, 0644)
}

func extractFileData(files []*ast.File) extractedFileData {
	res := extractedFileData{
		imports: make([]*ast.ImportSpec, 0),
		decls:   make([]ast.Decl, 0),
	}

	for _, f := range files {
		res.decls = append(res.decls, f.Decls...)
		res.imports = append(res.imports, f.Imports...)
	}

	return res
}

func parseDir(dir string) (*token.FileSet, []*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, nil, err
	}

	fset := token.NewFileSet()
	var files []*ast.File

	for _, entry := range entries {
		name := entry.Name()
		if !strings.HasSuffix(name, ".go") ||
			name == "getters.go" ||
			strings.HasSuffix(name, "_test.go") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return nil, nil, fmt.Errorf("parse %s: %w", name, err)
		}
		files = append(files, f)
	}
	return fset, files, nil
}

func collectImports(imports []*ast.ImportSpec) map[string]string {
	result := make(map[string]string)
	for _, imp := range imports {
		importPath := strings.Trim(imp.Path.Value, `"`)
		var alias string
		if imp.Name != nil && imp.Name.Name != "_" && imp.Name.Name != "." {
			alias = imp.Name.Name
		} else {
			alias = path.Base(importPath)
		}
		result[alias] = imp.Path.Value
	}

	return result
}

func collectStructs(fset *token.FileSet, decls []ast.Decl) []structInfo {
	var structs []structInfo
	for _, decl := range decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			si := structInfo{
				name:     typeSpec.Name.Name,
				recvName: string(unicode.ToLower([]rune(typeSpec.Name.Name)[0])),
			}

			for _, field := range structType.Fields.List {
				for _, ident := range field.Names {
					if ast.IsExported(ident.Name) {
						continue
					}
					si.fields = append(si.fields, fieldInfo{
						name:     ident.Name,
						typeName: exprToString(fset, field.Type),
					})
				}
			}

			if len(si.fields) > 0 {
				structs = append(structs, si)
			}
		}
	}

	return structs
}

func exprToString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	printer.Fprint(&buf, fset, expr)
	return buf.String()
}

func neededImports(structs []structInfo, allImports map[string]string) map[string]string {
	used := make(map[string]bool)
	for _, s := range structs {
		for _, f := range s.fields {
			parts := strings.FieldsFunc(f.typeName, func(r rune) bool {
				return r == '*' || r == '[' || r == ']' || r == ' ' || r == '(' || r == ')'
			})
			for _, p := range parts {
				if dot := strings.Index(p, "."); dot > 0 {
					used[p[:dot]] = true
				}
			}
		}
	}

	result := make(map[string]string)
	for alias, importPath := range allImports {
		if used[alias] {
			result[alias] = importPath
		}
	}
	return result
}

func generateSource(pkgName string, structs []structInfo, imports map[string]string) ([]byte, error) {
	var b strings.Builder

	//b.WriteString("// Code generated by getter-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n", pkgName)

	if len(imports) > 0 {
		// Sort import paths for deterministic output
		paths := make([]string, 0, len(imports))
		for _, p := range imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)

		// Build reverse map: quoted path -> alias
		aliasOf := make(map[string]string)
		for alias, p := range imports {
			aliasOf[p] = alias
		}

		if len(paths) == 1 {
			p := paths[0]
			alias := aliasOf[p]
			defaultAlias := path.Base(strings.Trim(p, `"`))
			if alias != defaultAlias {
				fmt.Fprintf(&b, "\nimport %s %s\n", alias, p)
			} else {
				fmt.Fprintf(&b, "\nimport %s\n", p)
			}
		} else {
			b.WriteString("\nimport (\n")
			for _, p := range paths {
				alias := aliasOf[p]
				defaultAlias := path.Base(strings.Trim(p, `"`))
				if alias != defaultAlias {
					fmt.Fprintf(&b, "\t%s %s\n", alias, p)
				} else {
					fmt.Fprintf(&b, "\t%s\n", p)
				}
			}
			b.WriteString(")\n")
		}
	}

	for _, s := range structs {
		for _, f := range s.fields {
			publicName := capitalize(f.name)
			fmt.Fprintf(&b, "\nfunc (%s *%s) %s() %s {\n\treturn %s.%s\n}\n",
				s.recvName, s.name, publicName, f.typeName, s.recvName, f.name)
		}
	}

	return format.Source([]byte(b.String()))
}

func capitalize(s string) string {
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
